---
name: Bump the Jenkins LTS baseline version in the POMs

definitions:
  archetypes:
    theme-plugin: &theme-plugin-path theme-plugin/src/main/resources/archetype-resources/pom.xml
    empty-plugin: &empty-plugin-path empty-plugin/src/main/resources/archetype-resources/pom.xml
    hello-world: &hello-world-path hello-world/src/main/resources/archetype-resources/pom.xml
    global-configuration: &global-config-path global-configuration/src/main/resources/archetype-resources/pom.xml

  updates:
    updateBaseline: &update-baseline
      kind: file
      sourceid: JenkinsBaselineMajorMinor
    updateBaselineSpec: &update-baseline-spec
      matchpattern: >-
        (.*<jenkins.baseline>)(.*)(</jenkins.baseline>.*)
      replacepattern: >-
        ${1}{{ source "JenkinsBaselineMajorMinor" }}${3}
    updateJenkinsVersion: &update-jenkins-version
      kind: file
      sourceid: JenkinsBaselinePatch
    updateJenkinsVersionSpec: &update-jenkins-version-spec
      matchpattern: >-
        (.*<jenkins.version>)(.*)(</jenkins.version>.*)
      replacepattern: >-
        ${1}${jenkins.baseline}.{{ source "JenkinsBaselinePatch" }}${3}

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  JenkinsBaseline:
    name: Get the latest Jenkins LTS baseline version
    kind: shell
    spec:
      # Use what is referred to as PreviousLTS in https://github.com/jenkins-infra/jenkins.io/blob/baf89a5513bf6dd038167a407a84d409c99b3450/updatecli/updatecli.d/jenkins-lts.yaml#L27
      command: bash ./.github/updatecli/scripts/jenkins-lts.sh 1
  JenkinsBaselineMajorMinor:
    name: Get the major and minor version of the latest Jenkins LTS baseline version
    kind: shell
    source: JenkinsBaseline
    dependson:
      - JenkinsBaseline
    spec:
      command: version="{{ source "JenkinsBaseline" }}" && echo "${version%.*}"
  JenkinsBaselinePatch:
    name: Get the patch version of the latest Jenkins LTS baseline version
    kind: shell
    source: JenkinsBaseline
    dependson:
      - JenkinsBaseline
    spec:
      command: version="{{ source "JenkinsBaseline" }}" && echo "${version##*.}"

conditions:
  jenkinsBaselineVersion:
    name: Check if the Jenkins baseline version is valid
    kind: jenkins
    sourceid: JenkinsBaseline

targets:
  # Theme Plugin Archetype
  updateThemePluginBaseline:
    <<: *update-baseline
    name: "Update the jenkins baseline in the theme plugin archetype"
    spec:
      <<: *update-baseline-spec
      file: *theme-plugin-path
  updateThemePluginJenkinsVersion:
    <<: *update-jenkins-version
    name: "Update the jenkins version in the theme plugin archetype"
    spec:
      <<: *update-jenkins-version-spec
      file: *theme-plugin-path
  # Empty Plugin Archetype
  updateEmptyPluginBaseline:
    <<: *update-baseline
    name: "Update the jenkins baseline in the empty plugin archetype"
    spec:
      <<: *update-baseline-spec
      file: *empty-plugin-path
  updateEmptyPluginJenkinsVersion:
    <<: *update-jenkins-version
    name: "Update the jenkins version in the empty plugin archetype"
    spec:
      <<: *update-jenkins-version-spec
      file: *empty-plugin-path
  # Global Configuration Archetype
  updateGlobalConfigBaseline:
    <<: *update-baseline
    name: "Update the jenkins baseline in the global configuration archetype"
    spec:
      <<: *update-baseline-spec
      file: *global-config-path
  updateGlobalConfigJenkinsVersion:
    <<: *update-jenkins-version
    name: "Update the jenkins version in the global configuration archetype"
    spec:
      <<: *update-jenkins-version-spec
      file: *global-config-path
  # Hello World Archetype
  updateHelloWorldBaseline:
    <<: *update-baseline
    name: "Update the jenkins baseline in the hello world archetype"
    spec:
      <<: *update-baseline-spec
      file: *hello-world-path
  updateHelloWorldJenkinsVersion:
    <<: *update-jenkins-version
    name: "Update the jenkins version in the hello world archetype"
    spec:
      <<: *update-jenkins-version-spec
      file: *hello-world-path

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Update Jenkins baseline version and BOM
    spec:
      labels:
        - dependencies
        - chore
