/*
 See the documentation for more options:
 https://github.com/jenkins-infra/pipeline-library/
*/
def recentLTS = "2.222.1"

buildPlugin(useAci: true, configurations: [
        [ platform: "linux", jdk: "8", jenkins: null ],
        [ platform: "windows", jdk: "8", jenkins: recentLTS, javaLevel: "8" ],
        [ platform: "linux", jdk: "11", jenkins: recentLTS, javaLevel: "8" ],
])
