name: Update CLI
on:
  # Allow to be run manually
  workflow_dispatch:
  schedule:
    # Run once per week (to avoid alert fatigue)
    - cron: '0 2 * * 1' # Every Monday at 2am UTC
  push:
  pull_request:
jobs:
  updatecli:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'jenkinsci'
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@41b9c8d707830a9daebaeaa84c1b62d60b779564 # v3.6.0

      - name: Run Updatecli in Dry Run mode
        run: updatecli diff --config ./.github/updatecli/updatecli.d --values ./.github/updatecli/values.github-action.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Updatecli in Apply mode
        if: github.ref == 'refs/heads/master'
        run: updatecli apply --config ./.github/updatecli/updatecli.d --values ./.github/updatecli/values.github-action.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
